spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
 
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #可以使用Config实现集中配置，使用$进行引入
    hostname: client
    status-page-url: http://127.0.0.1:8083/swagger-ui.html
